name: epubx
description: Epub Parser for Dart. Epub package fork. Suitable for use on the Server, the Web, or in Flutter
homepage: https://github.com/rbcprolabs/epubx.dart
issue_tracker: https://github.com/rbcprolabs/epubx.dart
version: 4.0.2

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  archive: ^4.0.4
  quiver: ^3.2.2
  path: ^1.9.1
  xml: ^6.5.0
  image: ^4.5.3
  collection: ^1.15.0

dev_dependencies:
  test: ^1.16.7
